### ISSUE TITLE
Instructor Review - Week 15

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [stasRevin/danceUpByStas#10]
I know you've put a lot of time and effort into your project! I'm really looking forward to seeing your completed application.  Good job using properties, creating small, single-purpose, testable methods, 

- [x] Project Plan and Journal have not been updated in roughly 2 months. Either update or remove so that prospective employers don't wonder why these are not current. 
- [x] At this point you could remove any placeholder.txt files that are no longer necessary.
- [x] Review restful naming standards: https://github.com/stasRevin/danceUpByStas/blob/6a2fcbec022f38f4c344a9517eb83a6cd4a09b93/src/main/java/com/instructorDayAvailabilityService/InstructorDayAvailabilityService.java#L18
- [x] This might be more readable with either an enumeration or an actual role value such as "instructor" or "student". Feels like a magic number. https://github.com/stasRevin/danceUpByStas/blob/6a2fcbec022f38f4c344a9517eb83a6cd4a09b93/src/main/java/com/danceUpByStas/controller/InsertUserDance.java#L52
- [x] Are these items needed in the session or would request work here? https://github.com/stasRevin/danceUpByStas/blob/6a2fcbec022f38f4c344a9517eb83a6cd4a09b93/src/main/java/com/danceUpByStas/controller/StudentSignIn.java#L68-L69 My concern about session is that if a dance or lesson is removed, how is the session updated to reflect that?
- [x] Remember to javadoc all classes and methods. 
- [x] It looks like you have some error pages for the else conditions. What happens if the database is down? Do you get any 500 errors that aren't handled by your current code? If so, adding an error page in your web.xml maybe a good idea as a "catch all".

**Comment by stasRevin** [comment]
Thank you for the feedback. As far as database goes down, here is the user experience for that:
![image](https://user-images.githubusercontent.com/32783730/49704796-4ba13380-fbdd-11e8-835a-2934781ddfb1.jpeg)

**Comment by stasRevin** [comment]
I agree that 1 is a magic number. The funny thing is that QA plug identified everything but that as a magic number. They probably hard coded to exclude 0 and 1 from their search for magic numbers.

**Comment by stasRevin** [comment]
The requested changes have been made except for the item about "sessions". The session data is accessed from multiple JSPs and the session data is updated on each update of the underlying data.

**Comment by stasRevin** [comment]
Thank you!
