### ISSUE TITLE
Instructor Feedback - Checkpoint 2

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [stasRevin/danceUpByStas#5]
Excellent job with progress on all aspects of your project! There are so many things "right" here that I would bring down GitHub commenting on them all :) You are well ahead of checkpoint 2, so I'm going to use this as more of a code review than the checkpoint review. Some of these items are very likely already on your radar, but I also didn't want to lose track of them, just in case...

- [x] What are your thoughts on how some of the very long methods might be refactored? Examples https://github.com/stasRevin/danceUpByStas/blob/ae12b1eb8d1d75de5c3b7325d7a76fde5f2cddce/src/main/java/com/danceUpByStas/controller/InsertInstructorSchedule.java#L25-L107 and https://github.com/stasRevin/danceUpByStas/blob/ae12b1eb8d1d75de5c3b7325d7a76fde5f2cddce/src/main/java/com/danceUpByStas/controller/UserSignUp.java#L42-L115
- [x] Opportunity to refactor here to avoid duplicating these two lines: https://github.com/stasRevin/danceUpByStas/blob/ae12b1eb8d1d75de5c3b7325d7a76fde5f2cddce/src/main/java/com/danceUpByStas/controller/InstructorProfileUpdate.java#L32-L33
- [x] Could this be handled by the generic dao? https://github.com/stasRevin/danceUpByStas/blob/ae12b1eb8d1d75de5c3b7325d7a76fde5f2cddce/src/main/java/com/danceUpByStas/persistence/UserRoleDao.java#L31

**Comment by stasRevin** [comment]
Thank you, Paula, for the feedback. I agree with all of your suggestions, to that, I committed and pushed changes containing some refactoring. The commit for that is here https://github.com/stasRevin/danceUpByStas/commit/b7f125e5ae3767ca3f506ebde00ea076f3c0d598?diff=split
