### ISSUE TITLE
Week 9 Rest Service Feedback

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [stasRevin/danceUpByStas#8]
Nice job producing a restful service in your project. 

- [ ] Note that specifying @produces does not automatically create those various types, you still need to build those responses. https://github.com/stasRevin/danceUpByStas/blob/81ed053fdbaa14f9b466313bf14597d5b0a8670e/src/main/java/com/danceDescriptionService/DanceDescriptionService.java#L32.

**Comment by sasha802** [comment]
Got annotations in the entity class to build JSON or XML. Thank you.
