### ISSUE TITLE
danceUpByStas Code Review

### ISSUE THREAD

**Issue by sasha802** [stasRevin/danceUpByStas#9]
# Design/Code Review 3

#### Reviewer: Oleksandra Ponomarova
###Code review tools: QAPlug, Checkstyle, FindBugs

|Category|Criteria|Rating/Comments|
|--------|---------|---------------|
|**Project Overview**|| |
||Which planned functionality has been met? |Stas met all the planned functionality. The application provides users with an ability to create a personalized profile and find a dance instuctor(s) in the area. Applications functionality: schedule a lesson, send a notification, search instructors in the area
|| What planned functionality has not been met? | All functionality has been implemented.
||Describe the GitHub history and what it demonstrates about the project progress during the semester.| Started with creating the project plan. Did front end jsp, hibernate and authentication. Was consistent with project plan and the course. |
||Describe how peer and instructor feedback/recommendations were incorporated into the project.|Implemented GenericDAO find by property mentor. Refactored long method and broken down into small once. Change UI look and design. |
||Other comments/notes?| |
|**JSPs**|| |
||Evaluate the JSPs for templating, business logic, data validation, overall look and feel.| JSP accommodate data validation and provides users with user friendly error messages. It has very nice flow and great design. Also was great to see mobile responsive design implemented.|
||Other comments/notes?| |
|**Java code quality**|Evaluate the code quality for the following and identify specific areas for improvement (class, method or line number) <li>single-purpose methods <li>well-structured project <li>descriptive naming of packages, classes, methods, variables <li>classes appropriately-sized  (no monster classes) <li> CPD (copy paste detection, meaning are the same lines of code repeated?) <li>are there candidates for super/subclass relationships, abstract classes, interfaces? <li>are any values hard-coded that should be in a properties file? <li>proper exception handling <li>proper error reporting to the user <li> code documentation |<li>The application uses single purpose methods<li>The application is well-structured.<li>The names of the variables and the methods and packages are fully spelled out and descriptive.<li>The classes are sized well no monster classes. The biggest class contains 209 lines of code.<li>No copy paste or repeated lines of code has been detecting in the application.<li>Application has one interface. There are no candidates for super, abstract classes or interfaces relationships.<li>Application utilizes .properties files in a great way. No hardcoded values that require to be placed in to the properties file.<li>Application handles exception on the compiled level. <li>Application reports error messages to the user in case of the error.<li>The code documentation should be done.
Other comments/notes?||
|**Logging**|Evaluate the use of logging, for example:<li>appropriate use of logging statements in the code for error logging and debugging <li>logging levels used - info, debug, error <li> no occurrences of  System.out.printlns or printStackTrace() <li> logging works on AWS deploy|<li>The application uses log4j2 to report errors locally.<li>The application mostly uses debug.<li>No occurrences of System.out.println or printStackTrace() found.<li>Should also be implemented to store logging statements on the AWS.|Other comments/notes?| |
|**Unit Tests**|Evaluate the unit tests, for example: <li>tests are truly a unit test rather than a high level functional test <li>test data is appropriately cleaned up or handled <li> there is full coverage of methods that perform business logic or utility functions <li>redundant code is eliminated by using set up and tear down methods, i.e., @Before, @After|<li>The tests are truly audit test.<li>The data has been appropriately cleaned up.<li>The business logic and utility functions are fully covered with unit testing.<li>The application uses @Before each method to eliminate redundant code.
|Other comments/notes?| |
|**Security**|Evaluate authentication/authorization:| |
||Is it implemented correctly and working locally as well as on AWS?|The application uses tomcat authentication. It is implemented correctly and it is working on the AWA and locally.
|Other comments/notes?| |
|**Web Service/API integration**|Evaluate the service/api integration, for example: <li> Which service/api is implemented? <li>How is  error handling of the service implemented? For example, what happens if the service is not available?|<li>The application implements zip radius service. Stas created 3 other services to be consumed with JavaScript.<li>Work needs to be done to handle the errors. If the service is not available user should be notified with user friendly message. |
||Other comments/notes?| |
|**Independent research topic**| What is the independent research topic?| |
||Is the independent research topic/technique implemented in the project?| Lamdas, Lombok, Java filters and listeners. Such independent research topics had been implemented in the application.|
||Other comments/notes?| |
|**Deployment**| Has the application been successfully deployed to AWS?| |
||Is the hosted application fully functioning?|The application has been deployed to AWS and the application has full functionality.|
||Other comments/notes?||

**Comment by sasha802** [comment]
![codereview](https://user-images.githubusercontent.com/35584625/49704748-98383f00-fbdc-11e8-8f7d-12e1bd2c717d.jpeg)

**Comment by pawaitemadisoncollege** [comment]
@sasha802 Which, if any, of the code quality items found should be corrected?

**Comment by sasha802** [comment]
Magic numbers could be corrected.

**Comment by stasRevin** [comment]
Requested changes have been made. Thank you.
